#########################################################################################################
#    Keep in mind that this plugin does not fully support HEX color codes. (#FF0000)                    #
#    You can use https://www.birdflop.com/resources/rgb/ to create your colors                          #
#    You can use old format [ยงxยงrยงrยงgยงgยงbยงb] or simply follow the pattern that's already used           #
#    Developer; padrewin                                                                                #
#    GitHub; https://github.com/padrewin                                                                #
#    Links: https://linktr.ee/padrewin || https://discord.mc-1st.ro                                     #
#########################################################################################################

# Plugin Prefix:
plugin-prefix: "&8ใยงxยง6ยงFยง0ยง0ยงCยงDEยงxยง7ยง6ยง0ยงBยงDยง0nยงxยง7ยงCยง1ยง6ยงDยง3dยงxยง8ยง3ยง2ยง1ยงDยง6eยงxยง8ยงAยง2ยงCยงDยง9rยงxยง9ยง1ยง3ยง7ยงDยงDSยงxยง9ยง7ยง4ยง2ยงEยง0cยงxยง9ยงEยง4ยงDยงEยง3yยงxยงAยง5ยง5ยง8ยงEยง6tยงxยงAยงBยง6ยง3ยงEยง9hยงxยงBยง2ยง6ยงEยงEยงCeใ&7ยป "

# Scythe Shard - item to upgrade your Scythe:
upgrade-item:
  name: "ยงxยง6ยงFยง0ยง0ยงCยงDโฏ ยงxยง6ยงFยง0ยง0ยงCยงDSยงxยง7ยง5ยง0ยงAยงDยง0cยงxยง7ยงBยง1ยง4ยงDยง3yยงxยง8ยง1ยง1ยงEยงDยง5tยงxยง8ยง7ยง2ยง8ยงDยง8hยงxยง8ยงDยง3ยง2ยงDยงBe ยงxยง9ยงAยง4ยง6ยงEยง1SยงxยงAยง0ยง5ยง0ยงEยง4hยงxยงAยง6ยง5ยงAยงEยง6aยงxยงAยงCยง6ยง4ยงEยง9rยงxยงBยง2ยง6ยงEยงEยงCd"
  lore:
    - "ยงaโฌ ยง7Use this item to upgrade your ยงxยง6ยงFยง0ยง0ยงCยงDEยงxยง7ยง6ยง0ยงBยงDยง0nยงxยง7ยงCยง1ยง6ยงDยง3dยงxยง8ยง3ยง2ยง1ยงDยง6eยงxยง8ยงAยง2ยงCยงDยง9rยงxยง9ยง1ยง3ยง7ยงDยงDSยงxยง9ยง7ยง4ยง2ยงEยง0cยงxยง9ยงEยง4ยงDยงEยง3yยงxยงAยง5ยง5ยง8ยงEยง6tยงxยงAยงBยง6ยง3ยงEยง9hยงxยงBยง2ยง6ยงEยงEยงCeยง"

# EnderScythe settings:
damage-players: false # Set to true if you want players to use this Scythe in PvP
enderscythe-damage: 20 # damage
enderscythe-cooldown: 500 # miliseconds || this means 0.5 seconds
enderscythe-range: 32
enderscythe-max-level: 2 # Max level for the EnderScythe (cannot be 0)

# Activate or deactivate your Scythe's particles in case your players are bothered by that:
enderscythe-particles: true

# Particle settings for each level
particle-settings:
  1:
    type: "PORTAL"
    count: 5
    offset: 0.5, 1, 0.5
    extra: 0
  2:
    type: "HEART"
    count: 1
    offset: 0.5, 1, 0.5
    extra: 0
  3:
    type: "REDSTONE"
    count: 10
    offsetX: 0.5
    offsetY: 1
    offsetZ: 0.5
    extra: 0
    color: "#FF0000" # Color of REDSTONE particles
    size: 1.0 # Size of particles
  4:
    type: "VILLAGER_HAPPY"
    count: 30
    offset: 0.5, 1, 0.5
    extra: 0
  5:
    type: "FLAME"
    count: 3
    offset: 0.5, 1, 0.5
    extra: 0

# Set world where EnderScythe can be used:
# if you don't put your world here, scythe won't work
enderscythe-use-worlds:
  - overworld
  - enter
  - your
  - world names
  - lobby

# EnderScythe display settings:
ender-scythe:
  name: "ยงxยง6ยงFยง0ยง0ยงCยงDEยงxยง7ยง6ยง0ยงBยงDยง0nยงxยง7ยงCยง1ยง6ยงDยง3dยงxยง8ยง3ยง2ยง1ยงDยง6eยงxยง8ยงAยง2ยงCยงDยง9rยงxยง9ยง1ยง3ยง7ยงDยงDSยงxยง9ยง7ยง4ยง2ยงEยง0cยงxยง9ยงEยง4ยงDยงEยง3yยงxยงAยง5ยง5ยง8ยงEยง6tยงxยงAยงBยง6ยง3ยงEยง9hยงxยงBยง2ยง6ยงEยงEยงCe"
  level: "ยง8ใ%scythe_level%ยง8ใ" # Don't ever change this placeholder except its color. Colors are safe to be edited. Same applies for below lore section
  lore:
    - "ยง4๐ก ยง7แดสษช๊ฑ ๊ฑแดสแดสแด แดแดษด แดแดแดส %enderscythe_damage% แดแดแดแดษขแด"
    - "ยงc๐ ยง7แดสษช๊ฑ ๊ฑแดสแดสแด สแด๊ฑ แด สแดษดษขแด แด๊ฐ %enderscythe_range% สสแดแดแด๊ฑ"
    - "ยงd๐ ยง7แดสษช๊ฑ ๊ฑแดสแดสแด สแด๊ฑ แด แดแดแดสแดแดแดกษด แด๊ฐ %enderscythe_cooldown% ๊ฑแดแดแดษดแด๊ฑ"
  lore-placeholders:
    - "%enderscythe_damage%"
    - "%enderscythe_range%"
    - "%enderscythe_cooldown%"
  laser-color: "#800080" # Laser hex color (#800080) this is default PURPLE
